#' Compute SPAROscores from pre-computed gene ranks
#'
#' Computes SPAROscores for one or more gene signatures using the rank matrix
#' and rank caps generated by \code{\link{get_ranks}}.
#'
#' SPAROscores quantify signature activity based on the normalized Spearman
#' footrule distance between observed signature gene ranks and a column-specific
#' rank cap. Higher scores indicate that signature genes tend to occupy higher
#' expression ranks, whereas lower scores indicate weaker signature activity.
#'
#' This function is implemented as an S4 generic and supports multiple input
#' formats for signatures, including character vectors, named lists,
#' GeneSet objects, and GeneSetCollection objects.
#'
#' @param ranks A numeric matrix of gene ranks named ranks returned by
#' \code{\link{get_ranks}}. Rows correspond to genes and columns
#' correspond to samples, cells, or spatial domains.
#'
#' @param rank_caps A named numeric vector containing the rank cap associated
#' with each column of ranks. Typically obtained from the
#' rank_caps component returned by \code{\link{get_ranks}}.
#'
#' When supplying custom rank caps, names should match the column names of
#' ranks.
#'
#' @param signatures Gene signature(s) to score.
#'
#' Supported inputs include:
#' \itemize{
#' \item A character vector representing a single gene signature.
#' \item A named list of character vectors representing multiple gene
#' signatures.
#' \item A GeneSet object.
#' \item A GeneSetCollection object.
#' }
#'
#' Gene identifiers must use the same naming convention as the row names of
#' ranks.
#'
#'
#' @param handle_missing_genes Character string specifying how signature genes
#' absent from ranks should be handled.
#'
#' Supported options are:
#' \describe{
#' \item{"skip"}{
#' Exclude missing genes from score calculation (default).
#' }
#'
#' \item{"impute"}{
#' Include missing genes by assigning them the capped rank value.
#' }
#' }
#'
#'
#' @param down_signatures Gene signature(s) to be considered for scoring
#'  the down-regulation effect. Supported inputs are same as signatures.
#'  If provided, names(down_signatures) must match names(signatures).
#'  Defaults to NULL.
#'
#' When down_signatures is not NULL,
#' Final Score <- Score(signatures) - Score(down_signatures)
#'
#'
#' @param prefix Character string to be appended before the headers of the
#' columns returning scores. Defaults to "".
#'
#'
#' @return
#' A numeric matrix of SPAROscores.
#'
#' For a single signature, the returned matrix contains one column named
#' "SPAROscore" and one row per sample, cell, or spatial domain.
#'
#' For multiple signatures, rows correspond to samples, cells, or spatial
#' domains and columns correspond to signatures.
#'
#' @details
#' The supplied signature genes are first matched against the genes available
#' in ranks. Missing genes are reported and handled according to
#' handle_missing_genes.
#'
#' For each sample, cell, or spatial domain, SPAROscores are computed as
#'  the normalized Spearmancfootrule distance between observed signature
#'  gene ranks and the column-specific rank cap.
#'
#' Rank caps typically correspond to the rank of the geometric mean expression
#' value estimated by \code{\link{get_ranks}}, although custom rank caps
#' may also be supplied.
#'
#' @export
#'
#' @examples
#'
#' counts <- matrix(
#' sample(0:10, 500, replace = TRUE),
#' nrow = 50,
#' dimnames = list(
#'     paste0("gene", 1:50),
#'     paste0("cell", 1:10)
#' )
#' )
#'
#' # Compute ranks and rank caps
#' rank_results <- get_ranks(counts)
#'
#' # Score a single gene signature
#' scores <- get_scores(
#' ranks = rank_results$ranks,
#' rank_caps = rank_results$rank_caps,
#' signatures = c("gene1", "gene3")
#' )
#'
#' # Score multiple signatures
#' scores <- get_scores(
#' ranks = rank_results$ranks,
#' rank_caps = rank_results$rank_caps,
#' signatures = list(
#' sigA = c("gene1", "gene3"),
#' sigB = c("gene2", "gene4", "gene6")
#' )
#' )
#'
#'
# set the generic for get_scores() methods
setGeneric("get_scores",
           function(ranks,
                    rank_caps,
                    signatures,
                    down_signatures = NULL,
                    handle_missing_genes = "skip",
                    prefix = "")
               standardGeneric("get_scores"))




# set the method for get_scores() where signatures is a character vector
#' Compute scores where signatures is a character vector
#' @rdname get_scores
#' @export
setMethod("get_scores",
          signature(signatures = 'character'),
          function(ranks,
                   rank_caps,
                   signatures,
                   down_signatures = NULL,
                   handle_missing_genes = "skip",
                   prefix = ""){

              #call the helper function
              sparoscores <- compute_sparoscores(
                  ranks = ranks,
                  rank_caps = rank_caps,
                  signatures = signatures,
                  handle_missing_genes = handle_missing_genes)

              # add columnnames
              sparoscores <- as.matrix(sparoscores)
              colnames(sparoscores) <- paste0(prefix, "SPAROscore")

              # calculative down-regulation scores when signature_down is given
              if(!is.null(down_signatures)){

                  #call the helper function for down-regulation scoring
                  sparoscores_down <- compute_sparoscores(
                      ranks = ranks,
                      rank_caps = rank_caps,
                      signatures = down_signatures,
                      handle_missing_genes = handle_missing_genes)

                  # add columnnames for negative scores
                  sparoscores_down <- as.matrix(sparoscores_down)
                  colnames(sparoscores_down) <- paste0(prefix,
                                                       "SPAROscore")

                  # subtract down-regulation scores from original scores
                  sparoscores <- sparoscores - sparoscores_down

                  # codeblock to return both up and down signature scores
                  # subtract down-regulation scores from original scores
                  # sparoscores_combined <- sparoscores - sparoscores_down
                  #
                  # # alter the columnames of up, down and combined scores
                  # colnames(sparoscores) <- paste0(colnames(sparoscores),
                  #                                 "_up")
                  #
                  # colnames(sparoscores_down) <- paste0(
                  #     colnames(sparoscores_down), "_down")
                  #
                  # colnames(sparoscores_combined) <- paste0(
                  #     colnames(sparoscores_combined), "_combined")
                  #
                  # # merge up, down and combined scores
                  # sparoscores = cbind(sparoscores,
                  #                     sparoscores_down,
                  #                     sparoscores_combined)
              }

              return(sparoscores)
          }
)


# set the method for get_scores() where signatures is a named list
#' Compute scores where signatures is a named list
#' @rdname get_scores
#' @export
setMethod("get_scores",
          signature(signatures = 'list'),
          function(ranks,
                   rank_caps,
                   signatures,
                   down_signatures = NULL,
                   handle_missing_genes = "skip",
                   prefix = ""){

              #call the helper function with vapply
              sparoscores <- vapply(X = signatures,
                                   FUN = function(x){
                                              compute_sparoscores(
                                              ranks = ranks,
                                              rank_caps = rank_caps,
                                              signatures = x,
                                              handle_missing_genes =
                                                  handle_missing_genes)
                                          },
                                   FUN.VALUE = numeric(ncol(ranks)))
              colnames(sparoscores) <- paste0(prefix, colnames(sparoscores))

              # calculate down regulation scores when signature_down is given
              if(!is.null(down_signatures)){
                  # check if the signature names match b/w up and down lists
                  if(names(signatures) != names(down_signatures)){
                      stop("SPAROscore says: The names of gene sets in
                      down_signatures should match that of signatures")
                  }

                  # call helper function to score down-regulated genes
                  sparoscores_down <- vapply(X = down_signatures,
                                        FUN = function(x){
                                            compute_sparoscores(
                                                ranks = ranks,
                                                rank_caps = rank_caps,
                                                signatures = x,
                                                handle_missing_genes =
                                                    handle_missing_genes)
                                        },
                                        FUN.VALUE = numeric(ncol(ranks)))

                  # add column names for negative scores
                  colnames(sparoscores_down) <- paste0(prefix,
                                                colnames(sparoscores_down))

                  # subtract down-regulation scores from original scores
                  sparoscores <- sparoscores - sparoscores_down

              }

              return(sparoscores)
          }
)



# set the method for get_scores() where signatures is a GeneSet S4 class
#' Compute scores where signatures is a GeneSet S4 class
#' @rdname get_scores
#' @export
setMethod("get_scores",
          signature(signatures = 'GeneSet'),
          function(ranks,
                   rank_caps,
                   signatures,
                   down_signatures = NULL,
                   handle_missing_genes = "skip",
                   prefix = ""){

              #call the helper function
              sparoscores <- compute_sparoscores(
                  ranks = ranks,
                  rank_caps = rank_caps,
                  signatures = GSEABase::geneIds(signatures),
                  handle_missing_genes = handle_missing_genes)

              # add columnnames from the GeneSet object
              sparoscores <- as.matrix(sparoscores)
              colnames(sparoscores) <- paste0(prefix,
                                              GSEABase::setName(signatures))

              # calculative down-regulation scores when signature_down is given
              if(!is.null(down_signatures)){

                   # first check if the names of up and down signatures match
                  if(GSEABase::setName(signatures) !=
                     GSEABase::setName(down_signatures)){
                      stop("SPAROscore says: The names of gene sets in
                      down_signatures should match that of signatures")
                  }

                  #call the helper function for down-regulation scoring
                  sparoscores_down <- compute_sparoscores(
                      ranks = ranks,
                      rank_caps = rank_caps,
                      signatures = GSEABase::geneIds(down_signatures),
                      handle_missing_genes = handle_missing_genes)

                  # add columnnames for negative scores
                  sparoscores_down <- as.matrix(sparoscores_down)
                  colnames(sparoscores_down) <- paste0(prefix,
                                            GSEABase::setName(down_signatures))

                  # subtract down-regulation scores from original scores
                  sparoscores = sparoscores - sparoscores_down
              }
              return(sparoscores)
          }
)


# set the method for get_scores() where signatures is a GeneSetCollection
#' Compute scores where signatures is a GeneSetCollection S4 class
#' @rdname get_scores
#' @export
setMethod("get_scores",
          signature(signatures = 'GeneSetCollection'),
          function(ranks,
                   rank_caps,
                   signatures,
                   down_signatures = NULL,
                   handle_missing_genes = "skip",
                   prefix = ""){

              #call the helper function with vapply
              sparoscores <- vapply(X = GSEABase::geneIds(signatures),
                                    FUN = function(x){
                                        compute_sparoscores(
                                            ranks = ranks,
                                            rank_caps = rank_caps,
                                            signatures = x,
                                            handle_missing_genes =
                                                handle_missing_genes)
                                    },
                                    FUN.VALUE = numeric(ncol(ranks)))
              colnames(sparoscores) <- paste0(prefix, colnames(sparoscores))

              # calculate down regulation scores when signature_down is given
              if(!is.null(down_signatures)){
                  # check if the signature names match b/w up and down lists
                  if(names(signatures) != names(down_signatures)){
                      stop("SPAROscore says: The names of gene sets in
                      down_signatures should match that of signatures")
                  }

                  # call helper function to score down-regulated genes
                  sparoscores_down <- vapply(
                      X = GSEABase::geneIds(down_signatures),
                     FUN = function(x){
                         compute_sparoscores(
                             ranks = ranks,
                             rank_caps = rank_caps,
                             signatures = x,
                             handle_missing_genes =
                                 handle_missing_genes)
                     },
                     FUN.VALUE = numeric(ncol(ranks)))

                  # add column names for negative scores
                  colnames(sparoscores_down) <- paste0(prefix,
                                                colnames(sparoscores_down))

                  # subtract down-regulation scores from original scores
                  sparoscores = sparoscores - sparoscores_down

              }
              return(sparoscores)
          }
)
